In [1]:
#https://stackoverflow.com/questions/23566515/multiplication-of-1d-arrays-in-numpy

In [2]:
import numpy as np
import copy

In [3]:
def f(x):
    a=(x[0]-2)**4 + (x[0]-2*x[1])**2
    return a

In [92]:
def grad(x):
    a=np.array([4*(x[0]-2)**3 +2*(x[0]-2*x[1]) , -4*(x[0]-2*x[1])] )
    return(a)

In [5]:
grad((3,2))

array([ 8, -1])

In [6]:
np.matrix(grad((3,2)))*(np.matrix("1;2"))

matrix([[6]])

In [7]:
(np.matrix(grad((3,2))).T).shape

(2, 1)

In [95]:
def normgrad(x):
    a=grad(x)
    b=(a[0]**2 + a[1]**2)**(.5)
    return b

In [35]:
normgrad(np.array([3,4]))

11.180339887498949

# Line Search

In [52]:
alpha=0.5
def phi(x,alpha,d):
    ld=d*alpha
    y=x+ld
    phia=f(y)
    return phia

In [55]:
phi(np.array([0,0]),.5,np.array([3,3]))

1.5

In [56]:
alpha1=0
alpha2=np.inf
alpha0=0.5 #(given in the question as x_0 = 0.5)
rho=0.1 #( do )
t=3
l=[]
l.append(alpha)

In [57]:
def goldstein(alpha1,alpha2,x,alpha,d,t,rho):
    cond1=True
    cond2=False
    val=phi(x,alpha,d) 
    while cond2==False:
        if( phi(x,alpha,d)  > (f(x) +((grad(x)).dot(d))*rho*alpha)):
            cond1= False
        while cond1==False:
            alpha2=alpha
            alpha= (alpha1+alpha2)/2
            l.append(alpha)
            if (phi(x,alpha,d)  <= (f(x) +((grad(x)).dot(d))*rho*alpha)):
                cond1=True
            
        if (phi(x,alpha,d)  >= f(x) +((grad(x)).dot(d))*(1-rho)*alpha): 
            cond2= True
        else:
            alpha1=alpha
            if alpha2<np.inf:
                alpha=(alpha1+alpha2)/2
                l.append(alpha)
            else:
                alpha=t*alpha
                l.append(alpha)
    return alpha

In [87]:
def goldstein(alpha1,alpha2,x,alpha,d,t,rho):
    cond1=True
    cond2=False
    val=phi(x,alpha,d) 
    while cond2==False:
        if( phi(x,alpha,d)  > (f(x) +((grad(x)).dot(d))*rho*alpha)):
            cond1= False
        while cond1==False:
            alpha2=alpha
            alpha= (alpha1+alpha2)/2
            l.append(alpha)
            if (phi(x,alpha,d)  <= (f(x) +((grad(x)).dot(d))*rho*alpha)):
                cond1=True
        if (phi(x,alpha,d)  >= f(x) +((grad(x)).dot(d))*(1-rho)*alpha): 
            cond2= True
        else:
            alpha1=alpha
            if alpha2<np.inf:
                alpha=(alpha1+alpha2)/2
                l.append(alpha)
            else:
                alpha=t*alpha
                l.append(alpha)
    return alpha

# Fletcher Reeves

In [58]:
def p(lam,d):
    a=lam*d
    return a

In [59]:
def graddiff(y2,y1):
    a=grad(y2)
    b=grad(y1)
    c=b-a
    return c

In [60]:
def identity():
    a=np.matrix("1,0;0,1")
    return a

In [61]:
def D2(D1,p,q):
    a=np.matrix(p) #dimension is 1x2
    b=np.matrix(q) #dimension is 1x2
    ppt=a.T*a
    ptp=a*a.T
    qqt=b.T*b
    term2=ppt/ptp
    term3=(D1*qqt*D1)/(q*D1*q.T)
    final=D1 + term2 - term3 
    return final

# Algorithm

In [62]:
def dfponeiter(epsilon,xold,D):
    #listx=[]
    #listy=[]
    #listdirec=[]
    #k=1
    #j=1
    #listx.append(xold)
    #y=copy.deepcopy(xold)
    #listy.append(y)
    call=DFPone(epsilon,y,xold,j,k,listx,listy,listdirec,D)
    return call

In [81]:
def FRGfull(epsilon,xold):
    listx=[]
    listy=[]
    listdirec=[]
    k=1
    j=1
    d=-grad(xold)
    listx.append(xold)
    listy.append(xold)
    cond=True
    while cond==True:
        print(k)
        cond,k,a1,a2,a3,a4=FRGone(cond,epsilon,listy[-1],j,k,listx,listy,listdirec,d)
    return (k,a1,a2,a3,a4)

In [90]:
def FRGone(cond,epsilon,y,j,k,listx,listy,listdirec,d):
    if  normgrad(y)< epsilon :
        cond =False
        return (cond,k,j,listx,listy,listdirec)
    elif j==1 :
        listy.append(y)
        y1= copy.deepcopy(y)
        d1=d
        listdirec.append(d1)
        lam=goldstein(0,np.inf,y1,0.5,d1,2,.1)
        ld= d1*lam
        y2 = y1+ ld
        listy.append(y2)
        g=-grad(y2)
        term2= (normgrad(y2)/normgrad(y1))**2
        d2 = g + d1*term2 
        d=d2
        listdirec.append(d2)
        j =j+1
        rr= FRGone(cond,epsilon,y2,j,k,listx,listy,listdirec,d)
        return rr
    else:
        y2 =copy.deepcopy(y)
        d2=d
        listdirec.append(d2)
        lam=goldstein(0,np.inf,y2,0.5,d2,2,.1)
        ld = d2*lam
        y3 = y2 +ld
        listy.append(y3)
        listx.append(y3)
        y1 =y3
        k=k+1
        d1=-grad(y1)
    return (cond,k,j,listx,listy,listdirec)    
        

# Outputs

In [93]:
full=FRGfull(.01,(0,0))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222


KeyboardInterrupt: 

In [78]:
full

(7,
 1,
 [(1, 1),
  array([2.22044605e-16, 1.00000000e+00]),
  array([0.09615385, 0.73076923]),
  array([4.16333634e-16, 6.34615385e-01]),
  array([-0.00924556,  0.66050296]),
  array([1.26634814e-16, 6.69748521e-01]),
  array([0.000889  , 0.66725933])],
 [(1, 1),
  (1, 1),
  array([0.25, 1.25]),
  array([2.22044605e-16, 1.00000000e+00]),
  array([2.22044605e-16, 1.00000000e+00]),
  array([0.125, 0.75 ]),
  array([0.09615385, 0.73076923]),
  array([0.09615385, 0.73076923]),
  array([5.55111512e-17, 6.82692308e-01]),
  array([4.16333634e-16, 6.34615385e-01]),
  array([4.16333634e-16, 6.34615385e-01]),
  array([-0.01201923,  0.65865385]),
  array([-0.00924556,  0.66050296]),
  array([-0.00924556,  0.66050296]),
  array([-5.20417043e-17,  6.65125740e-01]),
  array([1.26634814e-16, 6.69748521e-01]),
  array([1.26634814e-16, 6.69748521e-01]),
  array([0.0011557 , 0.66743713]),
  array([0.000889  , 0.66725933])],
 [array([-3.,  1.]),
  array([-4., -0.]),
  array([ 1., -2.]),
  array([ 0.7692

In [79]:
FRGone(True,.001,np.array([0,0]),1,1,[np.array([0,0])],[np.array([0,0])],[],np.array([2,6]))

(True,
 2,
 2,
 [array([0, 0])],
 [array([0, 0]), array([0, 0])],
 [array([2, 6]), array([-0.6875,  0.4375])])